// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Mark struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Contents  string             `json:"contents"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}
